//
// Created by masy on 12.03.20.
//

#ifndef GUARDIAN_GAMESTATES_H
#define GUARDIAN_GAMESTATES_H

#define GUARDIAN_STATE_MENU 0x03u
#define GUARDIAN_STATE_PLACING 0x05u

#endif //GUARDIAN_GAMESTATES_H
