//
// Created by masy on 12.03.20.
//

#ifndef TALESOFCATVENTURE_GAMESTATES_H
#define TALESOFCATVENTURE_GAMESTATES_H

#define TOC_STATE_MENU 0x03u
#define TOC_STATE_PLACING 0x05u

#endif //TALESOFCATVENTURE_GAMESTATES_H
